### ISSUE TITLE
isNode isn't working correctly

### ISSUE THREAD

**Issue by rememberlenny** [Lorp/samsa#40]
https://github.com/Lorp/samsa/blob/1cfe12097b23d6bf1b5aee49c8bae1cc24f80dfa/src/samsa-core.js#L27

The CONFIG.isNode check is true when compiled in a typescript environment. This creates issues, so I'm temporarily going to create a samsa-core-browser.js that removes the node check.

**Comment by Lorp** [comment]
Good point. This flag might as well be called “isNotFrontEnd” since those are the only two states I am testing currently.

I also want to test for QuickJS at some point (which needs different file handling, among other things), so a generic “where I am?” config property, including browser, Node, TypeScript and QuickJS, would be useful.

**Comment by Lorp** [comment]
If we can work out reliable tests for each environment, that would be great. In the meantime, the CONFIG variable is in general intended for manual configuaration, so best to set this manually for TypeScript testing.

**Comment by rememberlenny** [comment]
Yep - Sounds good. Closing this for the time being.

Just for your note, when the file needs compiling before usage in the browser, the isNode == true. This can cause a problem, such as in my case, where the compiled version results in trying to access `fs` in the browser, although it shouldnt.
