### ISSUE TITLE
Support Woff, Woff2 format fonts

### ISSUE THREAD

**Issue by miracle-arrow** [Lorp/samsa#65]
I've uploaded woff, woff2 fonts, but it seems it's not supported for now.
Will this be supported on the future release?

Thank you.

**Comment by Lorp** [comment]
Support for WOFF and WOFF2 is avoided for now, because of the desire for Samsa GUI and the Samsa core library to be free of dependencies. However Samsa GUI should give an informative error message and suggest how to convert WOFF2 to TTF.

WOFF and WOFF2 are reasonable things to expect Samsa to do, so it could be interesting for Samsa to detect whether a decompression function is available (via another included script). Closing for now.
