### ISSUE TITLE
Add search by Unicode to the the "Filter by name or id" input box.

### ISSUE THREAD

**Issue by MariannaPaszkowska** [Lorp/samsa#87]
**Summary**
This feature request proposes the addition of a Unicode code point glyph search functionality in Samsa. This feature would improve the efficiency of testing for glyphs from complex scripts and rare characters not easily accessible through standard keyboards.

**Background**
In current usage, Samsa allows users to search for glyphs by typing the character itself into the string box, or searching by glyph name or id. 

**Suggested Implementation**

UI Enhancement: 
• Add this functionality to the "Filter by name or id" input box.
Other options:
• Add an input field specifically for Unicode points in the Samsa UI. 
• Add to the current string box for character entry. 

Syntax Proposal: The input could be in the standard Unicode notation (e.g., U+1F60A  for the smiling face emoji “😊”). 
Alternatively: u1F60A.

**Comment by Lorp** [comment]
Thanks for this. Good idea, fixed in 6198ed4e9bcf9103e6e5e947c552e6588fa4978f. You can now use any of the following formats in the "filter by string" field in order to filter by Unicode value: U+*nnnn*, u*nnnn*, &#x*nnnn*;, &#*nnnn*;.

For example, to enter the Euro sign €, type any of these:

* `U+20ac`
* `u20ac`
* `&#x20ac;`
* `&#8364;`

Unfortunately, Unicode IDs higher than 65535 such as U+1F60A ("😊") are not yet supported, awaiting integration of [samsa-core v2](https://github.com/Lorp/samsa-core).

**Comment by Lorp** [comment]
See issue #88
